@startuml
'https://plantuml.com/sequence-diagram

autonumber

actor Admin as ad
participant "HomePage" as home <<application>>
participant CreateSpecializationPage as page
participant SpecializationForm as form
participant specializationRoute as route
participant ISpecializationController as con1
participant specializationController as con2
participant ISpecializationService as ser1
participant specializationService as ser2
participant specialization as domain


ad -> home: Create a new Specialization 
activate home 
home -> page: /Specialization/CreateSpecializationPage
activate page
page -> form: SpecializationForm(handleSubmit)
activate form
form -> route: POST /api/specilization
activate route
route -> con1: createSpecialization
activate con1
con1 -> con2: createSpecialization
activate con2
con2 -> ser1: createSpecialization
activate ser1
ser1 -> ser2: createSpecialization
activate ser2
ser2 -> domain: create
activate domain
domain --> ser2: 201 Created
deactivate domain
ser2 --> ser1: 201 Created
deactivate ser2
ser1 --> con2: 201 Created
deactivate ser1
con2 --> con1: 201 Created
deactivate con2
con1 --> route: 201 Created
deactivate con1
route --> form: 201 Created
deactivate route
form --> page: 201 Created
deactivate form
page --> home: 201 Created
deactivate page
home --> ad: Specialization successfully created





@enduml