@startuml
'https://plantuml.com/component-diagram

top to bottom direction
 
interface "api" as API
interface "Auth0" as AUTH0
 
component "System" <<component>> <<system (C4)>> {
  component "Backend" <<component>><<container(c4)>> as backend{
  portin " " as B1
  portout " " as B2
  }
  
  
  portin " " as P1
  portout " " as P2
}
 

P1 -- B1
B2 -- P2
API -- P1
P2 --( AUTH0
@enduml