@startuml Sequence Diagram US1001
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

title Sequence Diagram US1001

actor "CostumerManager" as CM
participant ":Jobs4uBootstrap" as jobs4uBoot
participant ":BaseDemoBootstrap" as BaseDemoBoot
participant ":ClientUsersBootstrapper" as ClientUsersBoot
participant ":UsersBootstrapperBase" as UsersBootBase

participant ":AddUserController" as addUsrCtrl
participant ":AddJobs4uUserController" as addJobs4uUserCtrl
participant ":AddCostumerController" as addCostumerCtrl
participant ":Jobs4uUserBuilder" as jobs4uUserBuilder

participant ":AuthzRegistry" as authzReg
participant ":UserManagementService" as usrMgmtSvc
participant ":SystemUserBuilder" as sysUserBuilder

participant ":PersistencyContext" as PC
participant ":AppSettings" as APPS
participant ":RepositoryFactory" as RF

participant ":Jobs4uUserRepository" as jobs4uUsrRepo
participant ":UserRepository" as userRepo

participant ":SystemUser" as sysUsr
participant ":Jobs4uUser" as jobs4uUsr

participant ":CostumerRepository" as costumerRepo


activate CM

    CM --> jobs4uBoot : wants to create an Jobs4uUser
    activate jobs4uBoot

    jobs4uBoot -> BaseDemoBoot : execute()
    activate BaseDemoBoot

    BaseDemoBoot -> ClientUsersBoot : execute()
    activate ClientUsersBoot

    ClientUsersBoot -> UsersBootBase : registerJob4uUser(username,password,firstName, lastName, email,roles, address, phone)
    activate UsersBootBase

    UsersBootBase -> addJobs4uUserCtrl : addJobs4uUser(username,password,\n firstName, lastName, email,\n roles, address, phone)
    activate addJobs4uUserCtrl

    addJobs4uUserCtrl -> jobs4uUserBuilder : create()
    addJobs4uUserCtrl -> jobs4uUserBuilder : withInfo(username, password, firstName, lastName, email, roles)
    addJobs4uUserCtrl -> jobs4uUserBuilder : withAddress(address)
    addJobs4uUserCtrl -> jobs4uUserBuilder : withPhone(phone)
    addJobs4uUserCtrl -> jobs4uUserBuilder : build()
    activate jobs4uUserBuilder

    jobs4uUserBuilder -> authzReg : userService()
    activate authzReg

    authzReg -> usrMgmtSvc : create(userRepo, policy, encoder)
    activate usrMgmtSvc

    usrMgmtSvc -> authzReg : userService
    deactivate usrMgmtSvc

    authzReg -> jobs4uUserBuilder : userService
    deactivate authzReg

    jobs4uUserBuilder -> usrMgmtSvc : registerNewUser(username, password, firstName, lastName, email, roles, createdOn)
    activate usrMgmtSvc

    usrMgmtSvc -> sysUserBuilder : create(this.policy, this.encoder)
    usrMgmtSvc -> sysUserBuilder : with(username, password, name, email)
    usrMgmtSvc -> sysUserBuilder : withRoles(roles);
    usrMgmtSvc -> sysUserBuilder : build()
    activate sysUserBuilder

    sysUserBuilder -> sysUsr : create(this.username, this.password, this.name, this.email, this.roles, this.createdOn)
    activate sysUsr

    sysUsr -> sysUserBuilder : systemUser
    deactivate sysUsr

    sysUserBuilder -> usrMgmtSvc : systemUser
    deactivate sysUserBuilder

    usrMgmtSvc -> userRepo : save(systemUser)
    activate userRepo

    userRepo -> usrMgmtSvc : systemUser
    deactivate userRepo

    usrMgmtSvc -> jobs4uUserBuilder : systemUser
    deactivate usrMgmtSvc

    jobs4uUserBuilder -> jobs4uUsr : create(systemUser, address, phone)
    activate jobs4uUsr

    jobs4uUsr -> jobs4uUserBuilder : jobs4uUser
    deactivate jobs4uUsr

    jobs4uUserBuilder -> addJobs4uUserCtrl : jobs4uUser

    deactivate jobs4uUserBuilder

    addJobs4uUserCtrl -> PC : repositories()
    activate PC

    PC -> APPS : getRepositoryFactory()
    activate APPS

    APPS -> RF : getRepositoryFactory()
    activate RF

    RF -> APPS : repositoryFactory
    deactivate RF

    APPS -> PC : repositoryFactory
    deactivate APPS

    PC -> RF : jobs4uUsers()
    activate RF

    RF -> PC : jobs4uUserRepository
    deactivate RF

    PC -> addJobs4uUserCtrl : jobs4uUserRepository
    deactivate PC

    addJobs4uUserCtrl -> jobs4uUserRepository : save(jobs4uUser)
    activate jobs4uUserRepository

    jobs4uUserRepository -> addJobs4uUserCtrl : jobs4uUser
    deactivate jobs4uUserRepository

    addJobs4uUserCtrl -> UsersBootBase : jobs4uUser
    deactivate addJobs4uUserCtrl

    UsersBootBase -> ClientUsersBoot : jobs4uUser
    ClientUsersBoot -> UsersBootBase :  registerCustomer(jobs4uUser)
    UsersBootBase -> addCostumerCtrl : addCostumer(jobs4uUser)
    activate addCostumerCtrl

    addCostumerCtrl -> PC : repositories()
    activate PC

    PC -> APPS : getRepositoryFactory()
    activate APPS

    APPS -> RF : getRepositoryFactory()
    activate RF

    RF -> APPS : repositoryFactory
    deactivate RF

    APPS -> PC : repositoryFactory
    deactivate APPS

    PC -> RF : costumers()
    activate RF

    RF -> PC : costumerRepository
    deactivate RF

    PC -> addCostumerCtrl : costumerRepository
    deactivate PC

    addCostumerCtrl -> costumerRepository : save(jobs4uUser)
    activate costumerRepository

    costumerRepository -> addCostumerCtrl : costumer
    deactivate costumerRepository

    addCostumerCtrl -> UsersBootBase
    deactivate addCostumerCtrl

    UsersBootBase -> ClientUsersBoot
    deactivate UsersBootBase

    ClientUsersBoot -> BaseDemoBoot
    deactivate ClientUsersBoot

    BaseDemoBoot -> jobs4uBoot
    deactivate BaseDemoBoot

    jobs4uBoot -> CM : Jobs4uUser created
    deactivate jobs4uBoot

deactivate CM

@enduml