@startuml
'https://plantuml.com/component-diagram

!define COLOR #ADD8E6 

skinparam  component {
    BackgroundColor COLOR
}

skinparam interface {
    BackgroundColor COLOR
    BorderColor black
}@startuml
 'https://plantuml.com/component-diagram
 
 !define COLOR #ADD8E6 
 
 skinparam  component {
     BackgroundColor COLOR
 }
 
 skinparam interface {
     BackgroundColor COLOR
     BorderColor black
 }
 
 component "<<component>>\n<<system (C4)>>\n    Sistema" as comp
 
 
 [comp] -- "filesystem API"
 "Admin" -- [comp]
 "Staff" -- [comp]
 "Patient" -- [comp]
 "Auth0" -- [comp]
 "SendGrid" -- [comp]
 
 @enduml

component "<<component>>\n<<system (C4)>>\n    Sistema" as comp


[comp] -- "filesystem API"
"Admin" -- [comp]
"Staff" -- [comp]
"Patient" -- [comp]

@enduml