@startuml US 6.2.17 - List Operation Requests

title Sequence Diagram

actor "Doctor" as user
participant "Page" as fe <<application>>
participant "ListOperationRequestPage" as listPage <<application>>
participant "OperationController" as con <<application>>
participant "OperationService" as service <<domain>>
participant "OperationRepository" as repo <<repository>>

user -> fe: Navigate to list operation requests page
activate user
activate fe

fe -> listPage: Load list operation requests page
activate listPage
listPage -> fe: (filter)
deactivate listPage

fe -> user : Display options to filter operation requests
deactivate fe

user -> fe: Selected filter option
activate fe
fe -> listPage: (filter)
activate listPage
listPage -> con: getOperationRequests(filter) \n [https://localhost:5001/api/OperationRequest]
activate con

con -> service: getOperationRequests(filter)
activate service

service -> repo: findOperationRequests(filter)
activate repo
repo --> service: matchingOperationRequests
deactivate repo

service --> con: matchingOperationRequests
deactivate service

con --> listPage: matchingOperationRequests
deactivate con

listPage -> listPage: Display operation request list



listPage -> fe: Display list of operation requests
deactivate listPage

fe -> user: Display list of operation requests
deactivate fe

deactivate user

@enduml